name: 'dbt_star_schema_medallion'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring Medallion Architecture layers
models:
  dbt_star_schema_medallion:
    bronze:
      +materialized: view
      +schema: bronze
      +tags: ['bronze', 'source_replication']
    silver:
      +materialized: view
      +schema: silver
      +tags: ['silver', 'cleansed']
    gold:
      +materialized: table
      +schema: gold
      +tags: ['gold', 'dimensional']

# tests configuration
tests:
  dbt_star_schema_medallion:
    +severity: warn